Implemented verifySig wrapper
kadena-io/pact-lang-api pull request #33
Opened 2022-04-11 00:07 UTC by raduciobanu22

`Pact.crypto.verifySig` was the default `nacl.sign.detached.verify` implementation which takes the parameters in a different format compared to what what `Pact.crypto.sign` returns. 
Specifically `sig` and `publicKey` have to be `Uint8Array` while `msg` has to be hashed with blake2b256.

2022-04-12 16:48 UTC, mightybyte requested changes
Thanks, this is a nice bit of convenience.  However, the change also breaks backwards compatibility for the exported `verifySig` function.  Can you leave the existing `verifySig` function as-is and add this functionality as an additional function?

Also would like @Randynamic to weigh in here as well.

2022-04-12 17:02 UTC, Randynamic requested changes

2022-04-12 17:05 UTC, Randynamic commented
Yes @mightybyte totally agree. I just had the same comments. 
@raduciobanu22 👍 for the tests btw.

2022-04-15 02:38 UTC, raduciobanu22 commented
Thanks for the feedback @mightybyte @Randynamic! I made the adjustments.

2022-06-16 15:06 UTC, merged